### ISSUE TITLE
Kod nawet nie startuje

### ISSUE THREAD

**Issue by luvh** [korona-science/homework-luvh#1]
Lokalnie wszystko śmiga, a tutaj kod się nawet nie odpala, co może być tego przyczyną?

**Comment by luvh** [comment]
@RouNNdeL

**Comment by luvh** [comment]
Poprawiłam odstępy, już totalnie nie wiem, co może być tego przyczyną
@amanujlo

**Comment by RouNNdeL** [comment]
Nadal masz złą indentacje, raz 4 raz 2

**Comment by RouNNdeL** [comment]
Otworzyłem twój plik w Colab i proszę:

![image](https://user-images.githubusercontent.com/22538735/76861568-16ae7280-685d-11ea-9444-13b932a71a66.png)

**Comment by luvh** [comment]
Nadal nie działa

**Comment by luvh** [comment]
Wcześniej wszystko ładnie śmigało, a teraz coś takiego:
![image](https://user-images.githubusercontent.com/48294226/76863787-5c206f00-6860-11ea-83cc-9d5fbd857c50.png)

**Comment by luvh** [comment]
Jak mam wszystkie funkcje zdefiniowane w oddzielnych sekcjach w jupyterze to działa - jak razem to już nie

**Comment by luvh** [comment]
juz poszlo, dzięki za pomoc
